spring.application.name=ashleyguevarra_phase1_log430

spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN

spring.datasource.url=jdbc:postgresql://localhost:5432/canbankx
spring.datasource.username=canbankx
spring.datasource.password=canbankx

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.zaxxer.hikari=DEBUG