flowchart TB
    subgraph CanBankX["CanBankX Banking API"]
        subgraph AccountService["account-service (2 instances derrière NGINX)"]
            Kyc[KycController]
            AccCtrl[AccountController]
            Consult[AccountConsultController]
            SagaInternal[InternalAccountSagaController]
        end
        subgraph TransferService["transfer-service (2 instances derrière NGINX)"]
            TransCtrl[TransferController]
            TransSvc[TransferService]
        end
    end

    subgraph Domaine
        Customer[Customer]
        Account[Account]
        Transfer[Transfer]
        Ledger[LedgerEntry]
        Audit[AuditLog]
    end

    Kyc --> Customer
    AccCtrl --> Account
    Consult --> Account
    Consult --> Ledger
    SagaInternal --> Account
    TransCtrl --> TransSvc
    TransSvc --> Transfer
    TransSvc --> SagaInternal

    subgraph Infra
        DB[(PostgreSQL)]
    end

    Account --> DB
    Customer --> DB
    Transfer --> DB
    Ledger --> DB
    Audit --> DB
