services:
  db:
    image: postgres:16
    container_name: brokerx_db
    environment:
      POSTGRES_DB: brokerx
      POSTGRES_USER: brokerx
      POSTGRES_PASSWORD: brokerx
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brokerx -d brokerx"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - brokerx_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: brokerx_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  brokerx_pgdata: